version: 2
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Authorize GCloud Command Line Tool
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode
      - run:
          name: Deploy To Google Cloud Functions
          command: |
            # Variables
            FUNCTION_NAME=hello
            ENTRYPOINT=hello
            GCP_PROJECT=datapush
            # Deploy command
            gcloud functions deploy $FUNCTION_NAME \
              --entry-point $ENTRYPOINT \
              --runtime nodejs10 \
              --trigger-http \
              --source ./ \
              --project $GCP_PROJECT
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master